config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get 'wir' => 'static_pages#wir'
  get 'kontakt' => 'static_pages#kontakt'
  get 'husum_tipps' => 'static_pages#husum_tipps'
  get 'sylt_tipps' => 'static_pages#sylt_tipps'

  get 'ferienwohnungen' => 'static_pages#ferienwohnungen'
  get 'ferienwohnungen_husum' => 'static_pages#ferienwohnungen_husum'
  get 'ferienwohnungen_sylt' => 'static_pages#ferienwohnungen_sylt'

  get 'woldsenstrasse1' => 'static_pages#woldsenstrasse1'
  get 'woldsenstrasse2' => 'static_pages#woldsenstrasse2'
  get 'rosenstrasse1' => 'static_pages#rosenstrasse1'
  get 'rosenstrasse2' => 'static_pages#rosenstrasse2'

  get 'paulstrasse' => 'static_pages#paulstrasse'
  get 'strandstrasse1' => 'static_pages#strandstrasse1'
  get 'strandstrasse2' => 'static_pages#strandstrasse2'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  # Controller Actions general pages 

  def home
  end

  def wir
  end

  def kontakt
  end

  def husum_tipps
  end  

  def sylt_tipps
  end  

  def ferienwohnungen
  end

  def ferienwohnungen_husum
  end
  
  def ferienwohnungen_sylt
  end

  # Controller Actions of specific apartements 

  def woldsenstrasse1
  end

  def woldsenstrasse2
  end

  def rosenstrasse1
  end

  def rosenstrasse2
  end

  def paulstrasse
  end
  
  def strandstrasse1
  end

  def strandstrasse2
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# General image paths
	def s3_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/General/#{path}"
	end

	# Strandstrasse1 
	def strandstraße1_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Sylt/Strandstrasse+Oben/Strandstrasse-Oben-#{path}.jpg"
	end

	def strandstraße1_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Sylt/Strandstrasse+Oben/Strandstrasse-Oben-#{path}.jpg"
	end 



	# Strandstrasse2
	def strandstraße2_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Sylt/Strandstrasse+Unten/Strandstrasse-Unten-#{path}.jpg"
	end

	def strandstraße2_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Sylt/Strandstrasse+Unten/Strandstrasse-Unten-#{path}.jpg"
	end



	# Paulstrasse
	def paulstraße_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Sylt/Paulstrasse/Paulstrasse-#{path}.jpg"
	end

	def paulstraße_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Sylt/Paulstrasse/Paulstrasse-#{path}.jpg"
	end



	# Woldsenstrasse1
	def woldsenstraße1_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Husum/Austernfischer/Austernfischer-#{path}.jpg"
	end

	def woldsenstraße1_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Husum/Austernfischer/Austernfischer-#{path}.jpg"
	end


	# Woldsenstrasse2
	def woldsenstraße2_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Husum/Kleiner+Austernfischer/Kleiner-Austernfischer-#{path}.jpg"	
	end

	def woldsenstraße2_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Husum/Kleiner+Austernfischer/Kleiner-Austernfischer-#{path}.jpg"	
	end




	# Rosenstrasse1
	def rosenstraße1_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Husum/Dat+lu%CC%88tte+Huus+1+OG/Dat-lu%CC%88tte-Huus-1-OG-#{path}.jpg"
	end

	def rosenstraße1_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Husum/Dat+lu%CC%88tte+Huus+1+OG/Dat-lu%CC%88tte-Huus-1-OG-#{path}.jpg"
	end



	# Rosenstrasse2
	def rosenstraße2_image(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Gross/Husum/Dat+lu%CC%88tte+Huus+EG/Dat-lu%CC%88tte-Huus-EG-#{path}.jpg"	
	end

	def rosenstraße2_image_small(path)
		@path = path 
		"https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Klein/Husum/Dat+lu%CC%88tte+Huus+EG/Dat-lu%CC%88tte-Huus-EG-#{path}.jpg"	
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_bootstrap_header.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 50px;">
  <div class="container-fluid boostrap_header">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>" style=""> <%= image_tag "logoooo.png" %> 
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Über uns", wir_path, style: "color: white;" %> </li>
          <li> <%= link_to "Husum Wohnungen", ferienwohnungen_husum_path, style: "color: white;" %> </li>
          <li> <%= link_to "Sylt Wohnungen", ferienwohnungen_sylt_path, style: "color: white;" %> </li>
          <li> <%= link_to "Kontakt", kontakt_path, style: "color: white;" %> </li>      
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: white;">Ferientipps<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "Sylt Tipps", sylt_tipps_path %> </li>
            <li> <%= link_to "Husum Tipps", husum_tipps_path %> </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.html.erb
<div class="row footer">

			<div class="col-md-4 col-md-offset-2 col-sm-5 col-sm-offset-1 kontakt_box">
				<h2> Kontakt auf Sylt </h2> 
				<h4> Ferienvermietung Hussmann </h4>
				<h4> 25890 Westerland </h4>
				<h4> <%= link_to "www.hussmann-sylt.de", 'http://www.hussmann-sylt.de/', target: "_blank" %> </h4>
				<h4> <a href="mailto:hussmansylt@t-online.de"> hussmansylt@t-online.de </a> </h4> 
				<h4> Tel.: 04651-836330 </h4>
			</div>

			<div class="col-md-4 col-sm-6 kontakt_box">
				<h2> Kontakt in Husum </h2> 
				<h4> Ferien an der Nordsee </h4>
				<h4> 25813 Husum </h4>
				<h4> <%= link_to "www.unsere-kueste.de", 'http://www.unsere-kueste.de/', target: "_blank" %> </h4>
				<h4> <a href="mailto:info@unsere-kueste.de"> info@unsere-kueste.de </a> </h4> 
				<h4> Tel: 04841-9041561 </h4>
			</div>

</div>

app/views/layouts/_header.html.erb
<div class="row header">
	<div class="col-xs-11 col-xs-offset-1">
		<a href="<%= root_path %>">
			<%= image_tag(s3_image("logo.jpg"), alt: "Urlaub im Herzen Nordfrieslands") %> 
		</a> 
			<ul> 
				<li> <%= link_to "Über uns", wir_path %> </li>
				<li> <%= link_to "Wohnungen", ferienwohnungen_path %> </li>
				<li> <%= link_to "Sylt Tipps", sylt_tipps_path %> </li>
				<li> <%= link_to "Husum Tipps", husum_tipps_path %> </li>
				<li> <%= link_to "Kontakt", kontakt_path %> </li>
		</ul> 
	</div> 
</div> 


		

app/views/layouts/_other_footer.html.erb
<div class="row other_footer">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
    <div class="left_side">
      <h2> Kontakt auf Sylt </h2> 
      <h4> Ferienvermietung Hussmann </h4>
      <h4> 25890 Westerland </h4>
      <h4> <a href="mailto:hussmansylt@t-online.de"> hussmansylt@t-online.de </a> </h4> 
      <h4> Tel.: 04651-836330 </h4>
    </div>
  </div> 
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0">
    <div class="right_side">
      <h2> Kontakt in Husum </h2> 
      <h4> Ferien an der Nordsee </h4>
      <h4> 25813 Husum </h4>
      <h4> <a href="mailto:info@unsere-kueste.de"> info@unsere-kueste.de </a> </h4> 
      <h4> Tel: 04841-9041561 </h4>
    </div> 
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlaub im Herzen Nordfrieslands</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--[if lt IE 9]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  	<![endif]-->
  </head>
  <body>

    <div class="container-fluid" style="padding: 0px;">
      <%= render 'layouts/bootstrap_header' %> 
      <%= yield %>
      <%= render 'layouts/other_footer' %> 
    </div> 

  </body>

  <!-- Google-Analytics tracking -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-72742514-1', 'auto');
    ga('send', 'pageview'); 
  </script>

</html>

app/views/static_pages/ferienwohnungen.html.erb
<h1 class="ferienwohnungen_heading" id="sylt"> Unsere Ferienwohnungen auf Sylt </h1> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/strandstra%C3%9Fe1_optimized.jpg"),strandstrasse1_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Wohnung Möwennest“ </h2> 
			<ul> 
				<li> 2 Personen + 1 Kind bis ca. 10 Jahren </li> 
				<li> 65 qm Wohnung mit 2 Zimmern  </li> 
				<li> sehr zentral und strandnahe  </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz </li> 
				<li> kostenfreies WLAN  </li> 
				<li> Preis ab 69 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", strandstrasse1_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/strandstra%C3%9Fe2_optimized.jpg"),strandstrasse2_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Wohnung Strandläufer“ </h2> 
			<ul> 
				<li> 2-4 Personen </li> 
				<li> 70 qm Wohnung mit 3 Zimmern </li> 
				<li> sehr zentral und strandnahe </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 89 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", strandstrasse2_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/paulstra%C3%9Fe_optimized.jpg"),paulstrasse_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Wohnung Seeschwalbe" </h2> 
			<ul> 
				<li> 2-4 Personen </li> 
				<li> 60 qm Wohnung mit 2,5 Zimmern </li> 
				<li> sehr zentral und strandnahe </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz in der Tiefgarage </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 89 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", paulstrasse_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<!-- HUSUM -->
<h1 class="ferienwohnungen_heading" id="husum"> Unsere Ferienwohnungen in Husum </h1> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/woldsen1_optimized.jpg"),woldsenstrasse1_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Wohnung Austernfischer"  </h2> 
			<ul> 
				<li> 2 Personen + ein Kind bis 10 Jahren </li> 
				<li> 68 qm Wohnung mit 2 Zimmern </li> 
				<li> sehr zentral, nur 600 Meter zum Schloss </li> 
				<li> Terrasse </li> 
				<li> eigener Parkplatz </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 49 €/Nacht + NK </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", woldsenstrasse1_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/woldsen2_optimized.jpg"),woldsenstrasse2_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Kleiner Austernfischer" </h2> 
			<ul> 
				<li> 2 Personen </li> 
				<li> auch für Alleinreisende geeignet </li> 
				<li> 38 qm Wohn und Schlafraum </li> 
				<li> sehr zentral, nur 600 Meter zum Schloss </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 35 €/Nacht + NK </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", woldsenstrasse2_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/rosen1_optimized.jpg"),rosenstrasse1_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Dat Lütte Huus" </h2> 
			<ul> 
				<li> 2 Personen </li>
				<li> 45 qm Studiowohnung mit Balkon </li> 
				<li> In Husums Altstadt </li>
				<li> nur 200 Meter zum Binnenhafen </li>
				<li> eigener Parkplatz </li>
				<li> kostenfreies WLAN </li>
				<li> Preis ab 45 €/Nacht + NK </li>
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", rosenstrasse1_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/rosen2_optimized.jpg"),rosenstrasse2_path) %> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 description">
			<h2> „Dat Lütte Huus" </h2> 
			<ul> 
				<li> 2 Personen </li>
				<li> 45 qm Studiowohnung </li>
				<li> mitten in der Altstadt </li>
				<li> nur 200 Meter zum Binnenhafen </li>
				<li> eigener Parkplatz </li>
				<li> kostenfreies WLAN </li>
				<li> Preis ab 45 €/Nacht + NK </li>
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", rosenstrasse2_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

app/views/static_pages/ferienwohnungen_sylt.html.erb
<h1 class="ferienwohnungen_heading" id="sylt"> Unsere Ferienwohnungen auf Sylt </h1> 

<div class="row wohnung">
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/strandstra%C3%9Fe1_optimized.jpg"),strandstrasse1_path) %> 
	</div>
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-0 description">
			<h2> „Wohnung Möwennest“ </h2> 
			<ul> 
				<li> 2 Personen + 1 Kind bis ca. 10 Jahren </li> 
				<li> 65 qm Wohnung mit 2 Zimmern  </li> 
				<li> sehr zentral und strandnahe  </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz </li> 
				<li> kostenfreies WLAN  </li> 
				<li> Preis ab 69 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", strandstrasse1_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/strandstra%C3%9Fe2_optimized.jpg"),strandstrasse2_path) %> 
	</div>
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-0 description">
			<h2> „Wohnung Strandläufer“ </h2> 
			<ul> 
				<li> 2-4 Personen </li> 
				<li> 70 qm Wohnung mit 3 Zimmern </li> 
				<li> sehr zentral und strandnahe </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 89 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", strandstrasse2_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

<div class="row wohnung">
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-1 image">
		<%= link_to(image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/paulstra%C3%9Fe_optimized.jpg"),paulstrasse_path) %> 
	</div>
	<div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-5 col-lg-offset-0 description">
			<h2> „Wohnung Seeschwalbe" </h2> 
			<ul> 
				<li> 2-4 Personen </li> 
				<li> 60 qm Wohnung mit 2,5 Zimmern </li> 
				<li> sehr zentral und strandnahe </li> 
				<li> in der Fußgängerzone </li> 
				<li> eigener Parkplatz in der Tiefgarage </li> 
				<li> kostenfreies WLAN </li> 
				<li> Preis ab 89 €/Nacht </li> 
			</ul>
			<%= link_to "WOHNUNG ANSCHAUEN", paulstrasse_path, class: "btn btn-large btn-warning" %>
	</div>
</div> 

app/views/static_pages/home.html.erb
<h2 id="page_title"> Nordfriesland von seiner schönsten Seite </h2>

<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-1 home_picture">
			<a href="<%= ferienwohnungen_sylt_path %>">
				<h2> Wohnungen auf Sylt </h2> 
				<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/sylt_strand_optimized.jpg",
							alt: "Der Husumer Hafen in seiner vollen Schönheit") %> 
			</a> 
		</div>

		<div class="col-xs-10 col-xs-offset-1 col-md-5 col-md-offset-0 home_picture">
			<a href="<%= ferienwohnungen_husum_path %>">	
				<h2> Wohnungen in Husum </h2> 
				<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/husum_hafen_optimized.jpg", alt: "Der Husumer Hafen in seiner vollen Schönheit") %> 
			</a> 
		</div>	
</div> 

app/views/static_pages/wir.html.erb
<div class="row ueber_uns">
	<div class="col-sx-10 col-sx-offset-1 col-md-4 col-md-offset-1 text">
		<h2> Liebe Feriengäste, </h2>
		<p>
			schön, dass Sie auf unsere ganz personliche Internetseite gefunden haben.
			Wir – Das sind Alexander und Sylvia mit unseren drei Kindern Johannes, Anna und Alex, sowie Hund Gismo. Wir sind eine mittelständige Einzelhändlerfamilie aus Husum, die sich seit fünf Jahren ein zweites Standbein mit Ferienwohnungen in Husum und Westerland aufbaut. Langsam sammelt sich ein kleines Portfolio an, welches wir Ihnen hier auf der Internetseite vorstellen. Jede Ferienwohnung wurde von uns persönlich gestaltet und regelmäßig schauen wir dort nach dem Rechten.
			Leider können wir unsere Wohnungen nicht selbst verwalten und haben Vertrauenspersonen in Husum und Westerland, die dies für uns übernehmen. Diese sind Frau Wiebke Volquardsen in Husum und
			Herr Johannes Hussmann in Westerland, die auch als Kontaktpersonen aufgeführt werden.
		</p> 
	</div>
	<div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-0 image">
		<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/new/fam_optimized.jpg", alt: "Familie Seikowsky - Urlaub im Herzen") %> 
		<%= link_to "HUSUM WOHNUNGEN", ferienwohnungen_husum_path, class: "btn btn-large btn-warning" %>
		<%= link_to "SYLT WOHNUNGEN", ferienwohnungen_sylt_path, class: "btn btn-large btn-warning" %>
		<%= link_to "KONTAKT", kontakt_path, class: "btn btn-large btn-warning" %> 
		<br> 
		<br>
		<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Kundenmeinung2.jpg", alt: "Was Kunden über die Ferienwohnung sagen") %> 
		<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Kundenmeinung3.jpg", alt: "Was Kunden über die Ferienwohnung sagen") %>
		<%= image_tag("https://s3-eu-west-1.amazonaws.com/urlaub-im-herzen/Kundenmeinung1.jpg", alt: "Was Kunden über die Ferienwohnung sagen") %>  
	</div> 
</div> 

<!-- Kundenmeinungen -->
<div class="row meinungen">
	<div class="col-xs-5 col-xs-offset-1">

	</div> 
	<div class="col-xs-5">

	</div> 
</div> 